from fengshen.models.transfo_xl_denoise.modeling_transfo_xl_denoise import TransfoXLDenoiseModel as TransfoXLModel
from .tokenization import TransfoXLTokenizer
from .generate import paraphrase_generate
